// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gluzzrbvqogiwvqdmdxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdsdXp6cmJ2cW9naXd2cWRtZHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwODg5MDUsImV4cCI6MjA2NjY2NDkwNX0.9QlERgg3wpt5Dkp8XnHwfeaXMVIRAKqzeu5dkoxWKYU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});